// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add_news__conatainer': string;
  'add_news__form': string;
  'header_news': string;
  'header_title': string;
  'news_activity': string;
  'news_category': string;
  'news_cb': string;
  'news_controls': string;
  'news_create': string;
  'news_date': string;
  'news_description': string;
  'news_form': string;
  'news_name': string;
  'news_row': string;
  'news_time': string;
}
export const cssExports: CssExports;
export default cssExports;
