// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'documents_page__header': string;
  'documents_page__header_icons': string;
  'documents_page__header_title': string;
  'documents_page__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
