// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'just_center': string;
  'two_columns': string;
  'underline': string;
  'view_claims__comments': string;
  'view_claims__container': string;
  'view_claims__description': string;
  'view_claims__header': string;
  'view_claims__header_title': string;
  'view_claims__icons': string;
  'view_claims__page_header': string;
  'view_claims__row': string;
  'view_claims__wrapper': string;
  'view_claims__wrapper_content': string;
}
export const cssExports: CssExports;
export default cssExports;
