// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'documents_item_add': string;
  'documents_item_add__container': string;
  'documents_item_add__controls': string;
  'documents_item_add__hidden': string;
  'documents_item_add__text_field': string;
  'form_documents': string;
  'form_documents__button': string;
  'form_documents__button_file': string;
  'form_documents__button_primary': string;
  'form_documents__button_secondary': string;
  'form_documents__file_field': string;
  'form_documents__header': string;
  'form_documents__header_title': string;
  'form_documents__text_field': string;
  'form_documents_add': string;
  'form_documents_text_fields': string;
}
export const cssExports: CssExports;
export default cssExports;
