// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'documents_item_add': string;
  'documents_item_add__button': string;
  'documents_item_add__button_primary': string;
  'documents_item_add__button_secondary': string;
  'documents_item_add__container': string;
  'documents_item_add__controls': string;
  'documents_item_add__hidden': string;
  'documents_item_add__status': string;
  'documents_item_add__text_field': string;
}
export const cssExports: CssExports;
export default cssExports;
