// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add_claims__container': string;
  'add_claims__header': string;
  'add_claims__row': string;
  'add_claims__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
