// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'wishes_page__container': string;
}
export const cssExports: CssExports;
export default cssExports;
