// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'comment_card__container': string;
  'comment_card__description': string;
  'comment_card__row': string;
}
export const cssExports: CssExports;
export default cssExports;
