// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'main_page_main_container': string;
}
export const cssExports: CssExports;
export default cssExports;
