// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error_component__container': string;
  'error_component__text': string;
}
export const cssExports: CssExports;
export default cssExports;
