// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'heading': string;
  'italic': string;
  'sub_title': string;
  'text': string;
  'title': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
