// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'edit_wishes__conatainer': string;
  'edit_wishes__form': string;
  'view_wishes__header': string;
  'view_wishes__header_title': string;
  'wishes_activity': string;
  'wishes_add__button': string;
  'wishes_add__button_save': string;
  'wishes_category': string;
  'wishes_cb': string;
  'wishes_controls': string;
  'wishes_create': string;
  'wishes_date': string;
  'wishes_description': string;
  'wishes_form': string;
  'wishes_name': string;
  'wishes_row': string;
  'wishes_time': string;
}
export const cssExports: CssExports;
export default cssExports;
