// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'wishes_page__container': string;
  'wishes_page__header_icons': string;
  'wishes_page__header_title': string;
  'wishes_page__wishes': string;
}
export const cssExports: CssExports;
export default cssExports;
