// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form_documents': string;
  'form_documents__button': string;
  'form_documents__button_primary': string;
  'form_documents__button_secondary': string;
  'form_documents__container': string;
  'form_documents__controls': string;
  'form_documents__header': string;
  'form_documents__header_title': string;
  'form_documents_edit': string;
  'form_documents_edit__item': string;
}
export const cssExports: CssExports;
export default cssExports;
