// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'paginator_comp__body': string;
  'paginator_comp__body_wrapper': string;
  'paginator_comp__container': string;
  'paginator_comp__loader': string;
  'paginator_comp__select': string;
  'paginator_comp__switcher': string;
  'paginator_comp__with_selector': string;
  'paginator_comp__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
