// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'documents_list_comp__body': string;
  'documents_list_comp__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
