// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card__button': string;
  'card__container': string;
  'card__head': string;
  'card__header_span_title': string;
  'card__row': string;
}
export const cssExports: CssExports;
export default cssExports;
