// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'documents_list_comp__content': string;
  'documents_list_comp__footer': string;
  'documents_list_comp__item': string;
  'documents_list_comp__item_head': string;
}
export const cssExports: CssExports;
export default cssExports;
