// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'claims_page__claims': string;
  'claims_page__header_icons': string;
  'claims_page__header_title': string;
}
export const cssExports: CssExports;
export default cssExports;
