// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'just_center': string;
  'two_columns': string;
  'underline': string;
  'view_wishes__comments': string;
  'view_wishes__container': string;
  'view_wishes__description': string;
  'view_wishes__header': string;
  'view_wishes__header_title': string;
  'view_wishes__icons': string;
  'view_wishes__page_header': string;
  'view_wishes__row': string;
  'view_wishes__wrapper': string;
  'view_wishes__wrapper_content': string;
}
export const cssExports: CssExports;
export default cssExports;
