// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header_icons': string;
  'header_news': string;
  'header_title': string;
  'news_body': string;
  'news_root': string;
}
export const cssExports: CssExports;
export default cssExports;
