// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'claims_page__container': string;
  'claims_page__header': string;
  'claims_page__header_container': string;
  'claims_page__header_icon': string;
  'claims_page__header_icons': string;
  'news_claims__description': string;
}
export const cssExports: CssExports;
export default cssExports;
