// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'wishes_card__button': string;
  'wishes_card__container': string;
  'wishes_card__head': string;
  'wishes_card__row': string;
}
export const cssExports: CssExports;
export default cssExports;
