// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'hidding': string;
  'icon': string;
  'icons': string;
  'logo': string;
  'menuActive': string;
}
export const cssExports: CssExports;
export default cssExports;
