// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'butterfly': string;
  'button': string;
  'header': string;
  'icons': string;
  'logo': string;
  'logout_button': string;
}
export const cssExports: CssExports;
export default cssExports;
