// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'status_component__container_info': string;
  'status_component__container_success': string;
  'status_component__text': string;
}
export const cssExports: CssExports;
export default cssExports;
