// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'disabled': string;
  'hidden': string;
  'menuButton': string;
  'navIcon': string;
  'navbar': string;
  'navbarItem': string;
}
export const cssExports: CssExports;
export default cssExports;
