// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'disabled_link': string;
  'header': string;
  'header_button': string;
  'navbar': string;
  'navbar_icon': string;
  'navbar_link': string;
  'navbar_links': string;
}
export const cssExports: CssExports;
export default cssExports;
