// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addcomment__btn': string;
  'addcomment__btn_container': string;
  'addcomment__container': string;
  'addcomment__textarea': string;
}
export const cssExports: CssExports;
export default cssExports;
