// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'news_page__container': string;
  'news_page__description': string;
  'news_page__header': string;
}
export const cssExports: CssExports;
export default cssExports;
