// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close': string;
  'news_page__container': string;
  'news_page__description': string;
  'news_page__header_container': string;
  'news_page__header_icons': string;
  'news_page__header_info': string;
  'news_page__header_title': string;
  'news_page_close': string;
  'news_page_open': string;
  'open': string;
}
export const cssExports: CssExports;
export default cssExports;
