// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'news_card': string;
  'news_card_content': string;
  'news_card_footer': string;
  'news_card_head': string;
  'news_card_head_date': string;
  'news_card_head_title': string;
}
export const cssExports: CssExports;
export default cssExports;
