// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header_title': string;
  'missions_cards_wrapper': string;
  'missions_header': string;
  'missions_root': string;
}
export const cssExports: CssExports;
export default cssExports;
