// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'confirm_component__button': string;
  'confirm_component__button_container': string;
  'confirm_component__container': string;
  'confirm_component__div_text': string;
}
export const cssExports: CssExports;
export default cssExports;
