// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'base-colors': string;
  'grid': string;
  'menuActive': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
