// localStorage
export const LOGIN_LOCALSTORAGE_KEY = "LOGIN_LOCALSTORAGE_KEY";
export const USERINFO_LOCALSTORAGE_KEY = "USERINFO_LOCALSTORAGE_QUERY";

// Authentication
export const LOGIN_QUERY = "LOGIN_QUERY";
export const USERINFO_QUERY = "USERINFO_QUERY";
export const ROLES_QUERY = "ROLES_QUERY";
export const REGISTRATION_QUERY = "REGISTRATION_QUERY";

// News
export const NEWS_QUERY = "NEWS_QUERY";

// notifications

export const NOTIFICATION_ADD = "NOTIFICATION_ADD";

// wishes

export const WISHES_QUERY = "WISHES_QUERY";

export const WISH_STATUSES = {
  IN_PROGRESS: "IN_PROGRESS",
  CANCELLED: "CANCELLED",
  OPEN: "OPEN",
  EXECUTED: "EXECUTED",
  READY: "READY",
  READY_CHECK: "READY_CHECK",
};

// nurse stations

export const NURSE_STATIONS_QUERY = "NURSE_STATIONS_QUERY";
export const NURSE_STATIONS_ID_QUERY = "NURSE_STATIONS_ID_QUERY";
export const NURSE_STATIONS_CREATE_QUERY = "NURSE_STATIONS_CREATE_QUERY";
export const NURSE_STATIONS_UPDATE_QUERY = "NURSE_STATIONS_UPDATE_QUERY";

// profile

export const PROFILE_SAVE_CHANGES_QUERY = "PROFILE_SAVE_CHANGES_QUERY";

// patiens

export const PATIENS_QUERY = "PATIENS_QUERY";
