// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add_claims__conatainer': string;
  'add_claims__form': string;
  'claims_activity': string;
  'claims_add__button': string;
  'claims_add__button_save': string;
  'claims_category': string;
  'claims_cb': string;
  'claims_controls': string;
  'claims_create': string;
  'claims_date': string;
  'claims_description': string;
  'claims_form': string;
  'claims_name': string;
  'claims_row': string;
  'claims_time': string;
  'header_claims': string;
  'header_title': string;
}
export const cssExports: CssExports;
export default cssExports;
