// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'claims_card__button': string;
  'claims_card__container': string;
  'claims_card__head': string;
  'claims_card__row': string;
}
export const cssExports: CssExports;
export default cssExports;
